//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.Linq;

namespace CardBringer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class karta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public karta()
        {
            this.oglas = new HashSet<oglas>();
            this.wishlist = new HashSet<wishlist>();
        }
    
        public int idKarta { get; set; }
        public string imeKarte { get; set; }
        public string opisKarte { get; set; }
        public string slikaKarte { get; set; }

        public void Spremi()
        {
            using (var context = new CardBringerDBEntities())
            {
                context.karta.Add(this);
                context.SaveChanges();
            }
        }
        public static BindingList<karta> DohvatiKarte()
        {
            BindingList<karta> lista = null;
            using (var context = new CardBringerDBEntities())
            {
                lista = new BindingList<karta>(context.karta.ToList());
            }
            return lista;
        }

        public static List<karta> TraziKarte(string pretrazivaniString)
        {
            List<karta> karte = new List<karta>();
            using (var context = new CardBringerDBEntities())
            {
                karte = new List<karta>(context.karta.Where(c => c.imeKarte.Contains(pretrazivaniString)).ToList());
            }
            return karte;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oglas> oglas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wishlist> wishlist { get; set; }
    }
}
