//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Linq;

namespace CardBringer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class kosharica
    {
        public int idKosarica { get; set; }
        public int idKorisnika { get; set; }
        public int idOglas { get; set; }
        public int kolicina { get; set; }
        public System.DateTime datum { get; set; }
        public byte kupljeno { get; set; }
        

        public void Spremi()
        {
            this.datum = DateTime.Today;
            this.kupljeno = 0;
            this.idKorisnika = korisnik.PrijavljeniKorisnik.idKorisnika;
            
            using (var context = new CardBringerDBEntities())
            {
                var result = context.kosharica.SingleOrDefault(c => c.idOglas == this.idOglas && c.kupljeno == 0);
                if (result != null)
                {
                    result.kolicina += kolicina;
                    context.SaveChanges();
                    return;
                }
                context.kosharica.Add(this);
                context.SaveChanges();
            }
        }


        public static void UkloniStavkuKosarice(int idKosarica)
        {
            using (var context = new CardBringerDBEntities())
            {
                var result = context.kosharica.SingleOrDefault(c => c.idKosarica == idKosarica);
                if (result == null) return;
                context.kosharica.Remove(result);
                context.SaveChanges();
            }
        }

        public static void StavkaKupljenaIliNe(int idKosarica, byte kupljeno)
        {
            using (var context = new CardBringerDBEntities())
            {
                var result = context.kosharica.SingleOrDefault(c => c.idKosarica == idKosarica);
                if (result == null) return;
                result.kupljeno = kupljeno;
                context.SaveChanges();
            }
        }


        public static List<object> DohvatiKosaricu(int kupljeno)
        {
            List<object> lista = new List<object>();
            using (var context = new CardBringerDBEntities())
            {
                var result = context.kosharica
                    .Join(context.korisnik, (o => o.idKorisnika), (p => p.idKorisnika),
                        (o, p) => new {
                            o,
                            p
                        })
                    .Where(c => c.p.idKorisnika == korisnik.PrijavljeniKorisnik.idKorisnika)
                    .Join(context.oglas, r => r.o.idOglas, s => s.idOglas,
                        (r, s) => new {
                            r,
                            s
                        })
                    .Join(context.karta, t => t.s.idKarta, u => u.idKarta,
                        (t, u) => new {
                            t,
                            u
                        })
                    .Join(context.korisnik, v => v.t.s.idKorisnik, z => z.idKorisnika, 
                        (v,z) => new
                        {
                            // v.t.r.o  - korisnikova ko�arica
                            // v.t.s    - oglas stavke u ko�arici korisnika
                            // v.u      - karta koja pripada oglasu iz stavke u ko�arici
                            // z        - korisnik koji je objavio oglas
                            

                            v.u.imeKarte,
                            v.u.opisKarte,
                            v.t.s.cijena,
                            v.t.r.o.kolicina,
                            z.ime,

                            v.t.s.idOglas,
                            v.u.slikaKarte,
                            v.t.r.o.kupljeno,
                            v.t.r.o.idKosarica
                        })
                    .Where(c => c.kupljeno == kupljeno)
                    .ToList();

                foreach (var r in result)
                {
                    lista.Add(r);
                }
            }
            return lista;
        }
        public virtual korisnik korisnik { get; set; }
        public virtual oglas oglas { get; set; }
    }
}
