//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Linq;

namespace CardBringer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class uloga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uloga()
        {
            this.korisnik = new HashSet<korisnik>();
        }
    
        public int idUloga { get; set; }
        public string nazivUloge { get; set; }

        public static string DohvatiNazivUloge(int id)
        {
            string uloga;
            using (var context = new CardBringerDBEntities())
            {
                uloga = context.uloga.FirstOrDefault(c => c.idUloga == id).nazivUloge;
            }
            return uloga;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<korisnik> korisnik { get; set; }
    }
}
