//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Linq;

namespace CardBringer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class wishlist
    {
        public int idKorisnik { get; set; }
        public int idKarta { get; set; }
        public int idWishlist { get; set; }

        public static List<object> DohvatiWishlist()
        {
            List<object> lista = new List<object>();
            using (var context = new CardBringerDBEntities())
            {
                var result = context.wishlist
                    .Join(context.karta, (o => o.idKarta), (p => p.idKarta),
                        (o, p) => new {
                            o.idWishlist,
                            p.imeKarte,
                            p.opisKarte,
                            p.slikaKarte,
                            o.idKorisnik
                        })
                    .Where(c => c.idKorisnik == CardBringer2.korisnik.PrijavljeniKorisnik.idKorisnika)
                    .ToList();

                foreach (var r in result)
                {
                    lista.Add(r);
                }
            }
            return lista;
        }

        public bool Spremi()
        {
            using (var context = new CardBringerDBEntities())
            {
                // Provjera postoji li navedena karta 
                if (context.wishlist.Any(c => c.idKarta == this.idKarta)) return false;
                context.wishlist.Add(this);
                context.SaveChanges();
            }
            return true;
        }

        public static void UkloniKartuSListeZelja(int id)
        {
            using (var context = new CardBringerDBEntities())
            {
                var result = context.wishlist.SingleOrDefault(c => c.idWishlist == id);
                if (result == null) return;
                context.wishlist.Remove(result);
                context.SaveChanges();
            }
        }

        public virtual karta karta { get; set; }
        public virtual korisnik korisnik { get; set; }
    }
}
